export use ./rustfmt-completions.nu *
export use ./rustup-completions.nu *
export use ./pnpm-completions.nu *
export use ./hx-completions.nu *
export use ./cargo.nu *
export use ./git.nu *
export use ./paru.nu *
export use ./systemctl.nu *
export use ./nmcli.nu *
